//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTTechNote
    {
        public int ID { get; set; }
        public int TechID { get; set; }
        public int TicketID { get; set; }
        public string Notes { get; set; }
        public System.DateTime TimeCreated { get; set; }
    
        public virtual TSTEmployee TSTEmployee { get; set; }
        public virtual TSTTicket TSTTicket { get; set; }
    }
}
