//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSTTicket()
        {
            this.TSTTechNotes = new HashSet<TSTTechNote>();
        }
    
        public int ID { get; set; }
        public int SubmitedByID { get; set; }
        public Nullable<int> TechID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ResolutionDate { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
        public int PriorityID { get; set; }
        public string Subject { get; set; }
    
        public virtual TSTEmployee TSTEmployee { get; set; }
        public virtual TSTEmployee TSTEmployee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSTTechNote> TSTTechNotes { get; set; }
        public virtual TSTTicketPriority TSTTicketPriority { get; set; }
        public virtual TSTTicketStatus TSTTicketStatus { get; set; }
    }
}
